### ISSUE TITLE
Latest release of sqlalchemy breaks zwift-offline

### ISSUE THREAD

**Issue by prmckinney** [zoffline/zwift-offline#120]
Using docker the default `pip install flask_sqlalchemy` now installs a 1.4+ version of sqlalchemy which isn't compatible with flash-sqlalchemy that gets installed (2.4.4)

From the 1.4 release notes:
The URL object is now an immutable named tuple. To modify a URL object, use the URL.set() method to produce a new URL object.
See also
The URL object is now immutable - notes on migration
References: #5526

This changes causes all DB operations to result in errors like:
`
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "/usr/src/app/zwift-offline/zwift_offline.py", line 1584, in before_first_request
    init_database()
  File "/usr/src/app/zwift-offline/zwift_offline.py", line 1526, in init_database
    version = db.session.execute('SELECT version FROM version').first()[0]
  File "<string>", line 2, in execute
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 104, in _proxied
    return self.registry()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4027, in __call__
    return self.class_(**local_kw)
  File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 138, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 943, in engine
    return self.get_engine()
  File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 962, in get_engine
    return connector.get_engine()
  File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 555, in get_engine
    options = self.get_options(sa_url, echo)
  File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 570, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 914, in apply_driver_hacks
    sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute
`

Manually rolling back to sqlalchemy 1.3.23 via `pip install SQLAlchemy==1.3.23`  resolves this issue.  I suspect uprev flask_sqlalchemy to 2.5+ would also resolve based on the release notes, but I've not tried.

**Comment by zoffline** [comment]
Thanks for the report! Much appreciated! I've forced a rebuild from scratch without using the problematic cached build step for the Docker Hub image and it appears to be working now that both flask_sqlalchemy 2.5+ and sqlalchemy 1.4+ get installed. Local Docker builds are working for me as it appeared that only the cached build image Docker Hub was using had the mismatched versions and the mismatch no longer occurs for fresh builds.

If this didn't resolve the issue please reopen.
