### ISSUE TITLE
DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by oldnapalm** [zoffline/zwift-offline#18]
I usually run Zwift on macOS, but today I used Windows 10 and got this error
```
127.0.0.1 - - [09/May/2019 13:22:59] "GET /api/profiles/1000/activities/ HTTP/1.1" 500 -
[2019-05-09 13:22:59,588] ERROR in app: Exception on /api/profiles/1000/activities/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Zwift\zwift-offline\zwift_offline.py", line 194, in api_profiles_activities
    cur.execute("SELECT * FROM activity WHERE player_id = ?", (str(player_id),))
DatabaseError: database disk image is malformed
```

**Comment by oldnapalm** [comment]
Actually it's also happening on Mac
```
[2019-05-09 11:11:50,176] ERROR in app: Exception on /api/profiles/1000/activities/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Volumes/Dados/Zwift/zwift-offline/zwift_offline.py", line 194, in api_profiles_activities
    cur.execute("SELECT * FROM activity WHERE player_id = ?", (str(player_id),))
DatabaseError: database disk image is malformed
```
Looks like zwift-offline.db got corrupted somehow.

Maybe it's because I swap the storage folder? (2 people use the same computer with different profiles)

Should I swap only profile.bin instead?

**Comment by oldnapalm** [comment]
Fixed the db and it's working, just lost the last activity. I think I didn't swap the storage with the app running, no idea what happened.

**Comment by oldnapalm** [comment]
It was probably because zwift-offline folder was in an ExFAT partition shared between macOS and Windows. After the last update some files gone missing after the partition was unmounted in macOS and mounted in Windows.
