### ISSUE TITLE
zwift companion app

### ISSUE THREAD

**Issue by naumovsergey** [zoffline/zwift-offline#210]
trying to connect to zoffline with patched companion app with certificate from sources. 
got error below

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "gevent\baseserver.py", line 34, in _handle_and_close_when_done
  File "gevent\server.py", line 233, in wrap_socket_and_handle
  File "gevent\_ssl3.py", line 796, in wrap_socket
  File "gevent\_ssl3.py", line 312, in __init__
  File "gevent\_ssl3.py", line 308, in __init__
  File "gevent\_ssl3.py", line 666, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:997)
2023-01-22T09:05:30Z <Greenlet at 0x179b9f131c0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x179ba29f460)> failed with SSLError

**Comment by oldnapalm** [comment]
Make sure you are using the correct certificate file (open with a text editor).

If you are downloading from browser, open the raw file before using "save as", otherwise it will save the html view instead of the actual file.

https://raw.githubusercontent.com/zoffline/zwift-offline/master/ssl/cert-zwift-com.pem

**Comment by naumovsergey** [comment]
fixed. thanks.
