### ISSUE TITLE
Docker container does not work correctly

### ISSUE THREAD

**Issue by peteh** [zoffline/zwift-offline#211]
When building the docker container manually using the provided Dockerfile and latest code I run into the issue that sqlalchemy seems to require text sanitization. 

I need to build it locally as I'm running it on a pi4. 

```bash
ERROR:zwift_offline:Exception on /api/auth [GET]
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/lib/python3.10/site-packages/flask/app.py", line 1812, in full_dispatch_request
    self.ensure_sync(func)()
  File "/usr/src/app/zwift-offline/zwift_offline.py", line 3197, in before_first_request
    check_columns(User, 'user')
  File "/usr/src/app/zwift-offline/zwift_offline.py", line 3164, in check_columns
    rows = db.session.execute("PRAGMA table_info(%s)" % table_name)
  File "/root/.local/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 709, in execute
    return self._proxied.execute(
  File "/root/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/root/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2022, in _execute_internal
    statement = coercions.expect(roles.StatementRole, statement)
  File "/root/.local/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 413, in expect
    resolved = impl._literal_coercion(
  File "/root/.local/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 639, in _literal_coercion
    return self._text_coercion(element, argname, **kw)
  File "/root/.local/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 632, in _text_coercion
    return _no_text_coercion(element, argname)
  File "/root/.local/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", line 602, in _no_text_coercion
    raise exc_cls(
sqlalchemy.exc.ArgumentError: Textual SQL expression 'PRAGMA table_info(user)' should be explicitly declared as text('PRAGMA table_info(user)')
INFO:zoffline:192.168.2.183 - - [2023-01-29 19:22:09] "GET /api/auth HTTP/1.1" 500 401 0.031106
```

Putting the sql queries into sqlalchemy.sql.text(xxx) before passing them to execute() seems to solve the issue though. However, I tried only for this particular query though and later queries are also failing.

**Comment by oldnapalm** [comment]
Thanks for the PR.
sqlalchemy was updated to version 2 which requires the execute argument to be text.

**Comment by oldnapalm** [comment]
There's another issue related to the sqlalchemy update I think, someone sent me this log, unfortunately I can't test now, maybe it's better to stick with version 1.4 for now

```ERROR:zwift_offline:Exception on /api/profiles/1/activities [GET]
Traceback (most recent call last):
  File "lib\sqlalchemy\cyextension\resultproxy.pyx", line 71, in sqlalchemy.cyextension.resultproxy.BaseRow._get_by_key_impl_mapping
KeyError: 'keys'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib\sqlalchemy\cyextension\resultproxy.pyx", line 88, in sqlalchemy.cyextension.resultproxy.BaseRow.__getattr__
  File "lib\sqlalchemy\cyextension\resultproxy.pyx", line 73, in sqlalchemy.cyextension.resultproxy.BaseRow._get_by_key_impl_mapping
  File "sqlalchemy\engine\cursor.py", line 835, in _key_fallback
sqlalchemy.exc.NoSuchColumnError: Could not locate column in row for column 'keys'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "flask\app.py", line 2525, in wsgi_app
  File "flask\app.py", line 1822, in full_dispatch_request
  File "flask\app.py", line 1820, in full_dispatch_request
  File "flask\app.py", line 1796, in dispatch_request
  File "zwift_offline.py", line 475, in wrapper
  File "flask_login\utils.py", line 290, in decorated_view
  File "zwift_offline.py", line 1703, in api_profiles_activities
  File "zwift_offline.py", line 934, in row_to_protobuf
  File "lib\sqlalchemy\cyextension\resultproxy.pyx", line 90, in sqlalchemy.cyextension.resultproxy.BaseRow.__getattr__
AttributeError: Could not locate column in row for column 'keys'
Exception: Could not locate column in row for column 'keys'
INFO:zoffline:127.0.0.1 - - [2023-01-30 16:01:34] "GET /api/profiles/1/activities HTTP/1.1" 500 401 0.004033
```

If you can investigate please open a PR, otherwise I will pin to sqlalchemy 1.4 for row, I don't have a computer to test.

**Comment by oldnapalm** [comment]
Maybe `row = row._mapping` before https://github.com/zoffline/zwift-offline/blob/cd1e30132d3a9d565ad6fecf7ea302158d1e0cea/zwift_offline.py#L934

**Comment by cdemer** [comment]
If someone can test: https://github.com/cdemer/zwift-offline/commit/5351f295fdd0747e7fb4e72a29d1e29b869d020d#diff-f4053a7fcb3c73ca8b58c6fb646b8f0e2c467edfad4759aa3a241f09b3fe2ca2

Executable: https://github.com/cdemer/zwift-offline/suites/10670793065/artifacts/533637128

**Comment by peteh** [comment]
For it was working without throwing errors in the logs at least. So I think this could be closed for now. 

Or anything else open?

**Comment by oldnapalm** [comment]
Someone reported the error `AttributeError: Could not locate column in row for column 'keys'` when row_to_protobuf is called (e.g. showing segment results), I believe it's caused by sqlalchemy 2.0 update and may be fixed using execute().mappings() but I can't test now.
