### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by Am1S** [zoffline/zwift-offline#215]
Good afternoon. I've been using zoffline on Mac OS for about a year. After the January updates, something happened and I can't log in to zwift. After a dozen attempts to reinstall and configure everything anew, I found out the following:

with zoffline turned off, logging into native account also fails if you register the keys in ~/Library/Application Support/Zwift/data/cacert.pem

as soon as I erase these keys, everything starts working.

the private key is uploaded to keychain and the trust setting is enabled

Info.plist is patched and the application is re-signed according to the instructions.

What am I doing wrong?

**Comment by Am1S** [comment]
I full reinstall macOS on my makbook. with ssd format. I install Zwift.app again and make all steps needed for start zoffile. When me make step 
_Using a text editor open ~/Library/Application Support/Zwift/data/cacert.pem
Append the contents of ssl/cert-zwift-com.pem to cacert.pem_

ZwiftApp stop login to  official server. When I delete these key and cert from cacert.pem - all work normal!

I don't use homebrew python now.

**Comment by Am1S** [comment]
When I try connect to zoffline with patcher cacert.pem zoffline give me error:

`127.0.0.1 - - [03/Feb/2023 17:22:30] "GET /gameassets/MapSchedule_v2.xml HTTP/1.1" 200 -
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 796, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 666, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1129)
2023-02-03T14:22:41Z <Greenlet at 0x109bdb400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x1098688e0 o)> failed with SSLZeroReturnError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 796, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 666, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1129)
2023-02-03T14:22:42Z <Greenlet at 0x109bdb400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x1098688e0 o)> failed with SSLZeroReturnError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 796, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 666, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1129)
2023-02-03T14:22:48Z <Greenlet at 0x109bdb400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x1098688e0 o)> failed with SSLZeroReturnError

`

**Comment by oldnapalm** [comment]
Maybe there are new requirements for self signed certificates on macOS (like there is for iOS, maximum expiration and other things). Unfortunately I don't have hardware to run modern macOS. You could try to create a certificate that fulfills the requirements for recent iOS.

**Comment by Am1S** [comment]
> 

I create new cert and key  using this instruction for *.zwift.com. create p12 and load to keychains. create key and cert files. copy key and cert to cacert in Zwift app.

No happy %(

INFO:zoffline:127.0.0.1 - - [2023-02-04 21:33:00] "GET /style/site.css HTTP/1.1" 304 182 0.001168
INFO:zoffline:127.0.0.1 - - [2023-02-04 21:33:00] "GET /style/background.jpg HTTP/1.1" 304 190 0.002011
INFO:zoffline:127.0.0.1 - - [2023-02-04 21:33:00] "GET /favicon.ico HTTP/1.1" 404 331 0.000820
127.0.0.1 - - [04/Feb/2023 21:33:02] "GET /gameassets/MapSchedule_v2.xml HTTP/1.1" 200 -
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 796, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/Users/amis/Library/Python/3.9/lib/python/site-packages/gevent/_ssl3.py", line 666, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1129)
2023-02-04T18:33:13Z <Greenlet at 0x103b68400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x103d1a100 o)> failed with SSLZeroReturnError

**Comment by oldnapalm** [comment]
I noticed some warnings about deprecated protocol using latest gevent and urllib versions, try downgrading (`pip install urllib3==1.26.13 gevent==22.10.1` or earlier).

**Comment by paul-grundmann** [comment]
Seems like you should only copy the certificate from the cert-zwift-com.pem from now on. I guess they changed the way they read the cacert.pem file in the client on MacOS. This fixed it on my side

**Comment by Am1S** [comment]
Thanks! great works!
