### ISSUE TITLE
Server Error (Trackback)

### ISSUE THREAD

**Issue by hollysheep** [zoffline/zwift-offline#216]
Hi,

i have zoffline installed on 3 devices and there is an error which seems to come from the tablet. for some reasons i don't understand sometimes the private key (from cert-zwift-com.pem) in the file cacert.pem is deleted (is this because i tried to login to the normal zwift server once?). when i try to connect to the offline server nothing works - of course. When i close zwift on the tablet and restart the server of one of the devices there is this error:

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.10/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.10/dist-packages/gevent/server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.10/dist-packages/gevent/_ssl3.py", line 796, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
  File "/usr/local/lib/python3.10/dist-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/usr/local/lib/python3.10/dist-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.10/dist-packages/gevent/_ssl3.py", line 666, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:997)
2023-02-03T11:01:18Z <Greenlet at 0x7fa985850d60: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7fa9857df1c)> failed with SSLError
```

when i add the key to cacert.pem ON THE CLIENT the error ON THE SERVER is gone. I dont' understand that. I understand why the connection is failed when the key is missing but not why there is (or isn't) an error on the server when something on the client is changed?

**Comment by oldnapalm** [comment]
The certificate is required in the client, otherwise login will fail and server will throw SSL error.

About cacert.pem reverting to the original, wasn't one of the updates? I've seen that happen a few times before. If it reverts every time you run the client, it's a new behavior. I will investigate when I return home by the end of next week.

**Comment by hollysheep** [comment]
I don't think this is happen every time but every time when i connect to the real zwift server (after deleting the lines in /etc/hosts).

**Comment by oldnapalm** [comment]
I could not reproduce this issue, cacert.pem is untouched after latest update and connecting to official server.

**Comment by hollysheep** [comment]
The same here. I don't understand what was wrong before. I'll see what happened with the next update. I think you can close it.
