### ISSUE TITLE
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:992) on MACOS

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#227]
I have a problem running zoffline in the MAC system. The code is as follows. Please help me to solve this problem

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gevent/server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gevent/_ssl3.py", line 796, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gevent/_ssl3.py", line 666, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:992)
2023-03-15T01:17:53Z <Greenlet at 0x10e0f1940: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x10e0a15a0 o)> failed with SSLZeroReturnError

**Comment by oldnapalm** [comment]
Did you edit cacert.pem according to the updated instructions?

> Append the contents of the SSL certificate ssl/cert-zwift-com.pem to cacert.pem (**only the certificate and not the included private key**)

See #215 for details.

**Comment by jricoclq** [comment]
Yes, complete all settings according to the tutorial, and finally run the log to report an error
And it need to log in on the zwift interface, but zwift can't log in or register a new account.

**Comment by jricoclq** [comment]
https://user-images.githubusercontent.com/102775665/225214840-c4ea4af4-9d1d-4242-a310-a7ccb33c5d0f.mp4

**Comment by oldnapalm** [comment]
Did you copy only the part from `-----BEGIN CERTIFICATE-----` to cacert.pem and not the `-----BEGIN PRIVATE KEY-----` part in the beginning?

If that's not the problem I hope someone using macOS can help, I only have a Windows machine currently.

**Comment by jricoclq** [comment]
I copied all the characters in cert-zwift-com to cacert.pem
But I can try it now, just copy CERTIFICATE. I will try it now. I will tell you the result. Thank you

**Comment by oldnapalm** [comment]
Since you already copied all the contents, make sure you delete the PRIVATE KEY part. For what I understand, the problem on macOS is having the private key in cacert.pem.

**Comment by jricoclq** [comment]
It's done, you help me found the solution, just tried it, and it's ready to run.
In this way, I can help my friends use zoffline happily.
Thank you very much.
