### ISSUE TITLE
Can't connect to the Zoffline Server (occurred in violation of protocol )

### ISSUE THREAD

**Issue by tomasmueller** [zoffline/zwift-offline#255]
A few month ago Zoffline worked perfect (client = android 9; server = win10/ubuntu). Yesterday i updated the server and the client to the latest versions and now i can't connect anymore. I made all steps 3 times re-installed zwift on my tabled several times. I made a copy of the cacert.pem, the new file (with the certificates) has the same ower and right. /etc/hosts is correct. The error occurs when zwift app is started to the client tries to connect to the server but something is wrong.

I have this error on the server:
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.8/dist-packages/gevent/server.py", line 233, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/usr/local/lib/python3.8/dist-packages/gevent/_ssl3.py", line 796, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
  File "/usr/local/lib/python3.8/dist-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/usr/local/lib/python3.8/dist-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/gevent/_ssl3.py", line 666, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)
2023-09-06T12:42:08Z <Greenlet at 0x7f31d2eb0360: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7f31d2f60f4)> failed with SSLEOFError
```

**Comment by oldnapalm** [comment]
Is it a rooted Android device? How old was the previous install? Notice that the certificates changed in January 2022.

Does it happen also with Windows server? If it's a Linux only issue try changing MinProtocol to TLSv1.0 in /etc/ssl/openssl.cnf (location may be different depending on your distro).

**Comment by tomasmueller** [comment]
Yes, Android is rootet. I have the problem with zoffline on Windows 10 and Linux.

I got it to work end of 2022 or beginning 2023 with the same tablet and notebook (as server) with the same ubuntu. I uninstalled zwift from my tablet before.

> Notice that the certificates changed in January 2022.

What does this mean? I've copied the certificate from the latest zoffline version to the client. So it should work, or?

**Comment by oldnapalm** [comment]
> What does this mean? I've copied the certificate from the latest zoffline version to the client. So it should work, or?

Means if you had the previous version in cacert.pem it would not work. With current version it should work.

Make sure you have the modules in requirements.txt, those are the versions known to work, even if not the latest.

Other than that, no idea what could be wrong. Just tested on my phone and it worked. Phone is not rooted though, I used the obb patcher to add the certificate.

**Comment by tomasmueller** [comment]
I copied the file ss/cert-zwift-com.pem to my tablet. Is this the working certificate? This was updated 2 years ago.

I reinstalled the requirements.

I don't use VPN or Proxy.

**Comment by tomasmueller** [comment]
I've no tested my home trainer but there are no errors when using "Android (non-rooted device)" howto.

I don't need that certification stuff without root but with root? Why?

**Comment by oldnapalm** [comment]
> I copied the file ss/cert-zwift-com.pem to my tablet. Is this the working certificate? This was updated 2 years ago.

Yes, this is the working certificate (updated Jan 21, 2022).

> I've no tested my home trainer but there are no errors when using "Android (non-rooted device)" howto.

The difference is that ZofflineObb patches cacert.pem before Zwift extracts it, because the filesystem cannot be modified if the device is not rooted. If that method works I suppose you are making some mistake appending the certificate to cacert.pem manually. Make sure you download the [raw file](https://raw.githubusercontent.com/zoffline/zwift-offline/master/ssl/cert-zwift-com.pem) and not the html view.

**Comment by oldnapalm** [comment]
Closing due to lack of activity. Feel free to reopen if issue still exists.
