### ISSUE TITLE
Cannot get zoffline working on MacBook Pro 2018 Running Sonoma 14.0

### ISSUE THREAD

**Issue by paul-gowers** [zoffline/zwift-offline#261]
I have Zwift working (1.0.122008) on my MacBook Pro (2018 model) running Sonoma 14.0.
I then followed the README to install and set up offline/zwift-offline.
When I start Zwift it gets to the launcher screen and I can pick Map and Climb.
I press Start Zwift and puts up the Zwift Shop splash and then starts loading Zwift itself.
A few messages are shown but it then fails to login.
It reports "Oops. Wrong email/password. Let's try this again"
The logging in the terminal window running sudo python3 ./standalone.py gives a lot of SSL/TLS errors (I have attached log which repeats this same Traceback sequence) making me think there is something wrong with the secure connectivity.

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gevent/ssl.py", line 785, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gevent/ssl.py", line 319, in __init__
    raise x
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gevent/ssl.py", line 315, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gevent/ssl.py", line 673, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1000)
2023-10-19T16:37:19Z <Greenlet at 0x10e27f560: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x10e73f310 o)> failed with SSLZeroReturnError

[stderr.log](https://github.com/zoffline/zwift-offline/files/13045516/stderr.log)

I have modified the keychain as documented and added the pem contents to the end of cacert.pem
I am running zwift-offline and Zwift on same machine so have not created server_ip.txt

I placed the NSAppTransportSecurity key near the end of /Applications/Zwift.app/Contents/Info.plist which was the only piece of guesswork. It seemed to follow the same xml pattern as the rest of the file:

...        <array>
                <string>ZwiftFondoZGA-Black.otf</string>
                <string>ZwiftFondoZGA-Medium.otf</string>
        </array>
<key>NSAppTransportSecurity</key>
<dict>  
    <key>NSExceptionDomains</key>
    <dict>
        <key>zwift.com</key>
        <dict>          
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>     
            <key>NSIncludesSubdomains</key>
            <true/>             
        </dict>         
    </dict>     
</dict> 
</dict> 
        
</plist>

I am not sure what the issue is, with software or with README.md instructions but I am stuck currently. 

Hopefully I am not being an idiot but that is entirely possible :-)

**Comment by oldnapalm** [comment]
When you added the certificate to cacert.pem did you add the entire file or just the certificate part?

> Append the contents of the SSL certificate ssl/cert-zwift-com.pem to cacert.pem (**only the certificate and not the included private key**)

You should append only from line 29 (`-----BEGIN CERTIFICATE-----`) on, otherwise it won't work, according to reports from other Mac users.

**Comment by paul-gowers** [comment]
Many thanks for your quick reply which has fixed the problem.

**Comment by paul-gowers** [comment]
Closing as resolved. Thanks
