### ISSUE TITLE
Why do I get an error when connecting to the server?

### ISSUE THREAD

**Issue by shijiekk** [zoffline/zwift-offline#288]
` - - [15/Dec/2023 13:18:29] "GET /gameassets/Zwift_Updates_Root/ HTTP/1.1" 200 -
Error trying to proxy: ConnectionResetError(104, 'Connection reset by peer')
- - [15/Dec/2023 13:18:29] "GET /gameassets/Zwift_Updates_Root/ HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('49.7.19.197', 2235)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/http/server.py", line 658, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/root/zwift-offline/standalone.py", line 154, in do_GET
    SimpleHTTPRequestHandler.do_GET(self)
  File "/usr/lib/python3.10/http/server.py", line 662, in do_GET
    f = self.send_head()
  File "/usr/lib/python3.10/http/server.py", line 706, in send_head
    return self.list_directory(path)
  File "/usr/lib/python3.10/http/server.py", line 818, in list_directory
    self.end_headers()
  File "/usr/lib/python3.10/http/server.py", line 534, in end_headers
    self.flush_headers()
  File "/usr/lib/python3.10/http/server.py", line 538, in flush_headers
    self.wfile.write(b"".join(self._headers_buffer))
  File "/usr/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
<gevent._ssl3.SSLSocket at 0x7f03fb622110 server=True, cipher='' object, fd=11, family=2, type=1, proto=0>: Invalid HTTP method: '\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03ø_\x83kCç\x9a<J¿7Ã\x07y\x80ùPûY\x1a\x96~ ¼êé\x17/¢SÏf \x9f\x90T/ëI-!²Úºu\x13\x8eJ\x1f£DFîV\x9c(Èý`TØE>èÞ\x00\x1cJJ\x13\x01\x13\x02\x13\x03À,À+Ì©À0À/Ì¨À\n'
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.10/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.10/dist-packages/gevent/server.py", line 234, in wrap_socket_and_handle
    return self.handle(ssl_socket, address)
  File "/usr/local/lib/python3.10/dist-packages/gevent/pywsgi.py", line 1577, in handle
    handler.handle()
  File "/usr/local/lib/python3.10/dist-packages/gevent/pywsgi.py", line 471, in handle
    self.socket.sendall(response_body)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_ssl3.py", line 537, in sendall
    return socket.sendall(self, data, flags)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 699, in sendall
    return _sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 409, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 338, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_ssl3.py", line 511, in send
    return socket.send(self, data, flags, timeout)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer
2023-12-15T05:18:29Z <Greenlet at 0x7f03fb59b560: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7f03fb58888)> failed with ConnectionResetError

 - - [15/Dec/2023 13:18:44] "GET / HTTP/1.1" 200 -
65.49.1.102 - - [15/Dec/2023 13:21:34] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00{\x01\x00\x00w\x03\x03ëpãÃÅ¼\xadåf\xad\x9aÛ¬ÇÔÀ«£\x94\x8aÁ]`~9º\x82\x12\x98/2\x00\x00\x00\x1aÀ/À+À\x11À\x07À\x13À')
- - [15/Dec/2023 13:21:34] "{wëpãÃÅ¼­åf­Û¬ÇÔÀ«£Á]`~9ºÀ/À+ÀÀÀÀ       ÀÀ" 400 -
 - - [15/Dec/2023 13:24:38] code 501, message Unsupported method ('POST')
 - - [15/Dec/2023 13:24:38] "POST /Autodiscover/Autodiscover.xml HTTP/1.1" 501 -`

zwift:
Zwift encountered the following error: An SSL error has occurred and a secure connection to the server cannot be made.. Please check your internet connection and try again. If the problem persists, please contact Zwift Support with the error code ZLM04. Would you like to go to Zwift Support now?

This is the log。
why？
Did I open a lot of ports?

**Comment by fatsbrown** [comment]
Try creating a file `cdn-proxy.txt` in the storage directory.

If the error persists, try to edit `standalone.py` and delete lines 38 to 60. Also delete `cdn-proxy.txt` from storage.

Most of those errors in log are normal if you expose zoffline to the internet, they are requests from bots/worms.

**Comment by fatsbrown** [comment]
Actually looks like you are using an old version of zoffline, try to update first.

> File "/root/zwift-offline/standalone.py", line 154, in do_GET
> SimpleHTTPRequestHandler.do_GET(self)

In current version line 154 is not in that function.

**Comment by shijiekk** [comment]
I did what you said     but it still didn't work.
`<gevent.ssl.SSLSocket at 0x7fcfe7b5d2a0 server=True, cipher='' object, fd=11, family=2, type=1, proto=0>: (from ('115.171.198.198', 10912)) Expected GET method; Got command='\x16\x03\x03\x00\xad\x01\x00\x00©\x03\x03e|VÍáY'; path='½Ò'; raw='\x16\x03\x03\x00\xad\x01\x00\x00©\x03\x03e|VÍáY\x0b½Ò\n'
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.10/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.10/dist-packages/gevent/server.py", line 210, in wrap_socket_and_handle
    return self.handle(ssl_socket, address)
  File "/usr/local/lib/python3.10/dist-packages/gevent/pywsgi.py", line 1700, in handle
    handler.handle()
  File "/usr/local/lib/python3.10/dist-packages/gevent/pywsgi.py", line 581, in handle
    self.socket.sendall(response_body)
  File "/usr/local/lib/python3.10/dist-packages/gevent/ssl.py", line 544, in sendall
    return socket.sendall(self, data, flags)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 702, in sendall
    return _sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 391, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 320, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.10/dist-packages/gevent/ssl.py", line 518, in send
    return socket.send(self, data, flags, timeout)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 725, in send
    return self._sock.send(data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer
2023-12-15T13:38:20Z <Greenlet at 0x7fcfe7ad1e40: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7fcfe7bace8)> failed with ConnectionResetError

<gevent.ssl.SSLSocket at 0x7fcfe7b5d2a0 server=True, cipher='' object, fd=11, family=2, type=1, proto=0>: (from ('115.171.198.198', 10913)) Invalid HTTP method: '\x16\x03\x03\x00\xad\x01\x00\x00©\x03\x03e|VÍÜ.\x91Q_6m\n'
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.10/dist-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/usr/local/lib/python3.10/dist-packages/gevent/server.py", line 210, in wrap_socket_and_handle
    return self.handle(ssl_socket, address)
  File "/usr/local/lib/python3.10/dist-packages/gevent/pywsgi.py", line 1700, in handle
    handler.handle()
  File "/usr/local/lib/python3.10/dist-packages/gevent/pywsgi.py", line 581, in handle
    self.socket.sendall(response_body)
  File "/usr/local/lib/python3.10/dist-packages/gevent/ssl.py", line 544, in sendall
    return socket.sendall(self, data, flags)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 702, in sendall
    return _sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 391, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 320, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.10/dist-packages/gevent/ssl.py", line 518, in send
    return socket.send(self, data, flags, timeout)
  File "/usr/local/lib/python3.10/dist-packages/gevent/_socketcommon.py", line 725, in send
    return self._sock.send(data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer
2023-12-15T13:38:20Z <Greenlet at 0x7fcfe7ad1e40: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7fcfe7bace8)> failed with ConnectionResetError`

`if getattr(sys, 'frozen', False):
    # If we're running as a pyinstaller bundle
    SCRIPT_DIR = sys._MEIPASS
    EXE_DIR = os.path.dirname(sys.executable)
    STORAGE_DIR = "%s/storage" % EXE_DIR
    PACE_PARTNERS_DIR = '%s/pace_partners' % EXE_DIR
else:
    SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
    STORAGE_DIR = "%s/storage" % SCRIPT_DIR
    PACE_PARTNERS_DIR = '%s/pace_partners' % SCRIPT_DIR

CDN_DIR = "%s/cdn" % SCRIPT_DIR
CDN_PROXY = os.path.isfile('%s/cdn-proxy.txt' % STORAGE_DIR)
#if not CDN_PROXY:
    # If CDN proxy is disabled, try to resolve zwift.com using Google public DNS
#    try:
#        import dns.resolver
 #       resolver = dns.resolver.Resolver(configure=False)
#        resolver.nameservers = ['8.8.8.8', '8.8.4.4']
        #resolver.cache = dns.resolver.Cache()
        #resolver.resolve('zwift.com')
       # # If succeeded, patch create_connection to use resolver
      #  from urllib3.util import connection
     #   orig_create_connection = connection.create_connection
    #    def patched_create_connection(address, *args, **kwargs):
          #  try:
         #       host, port = address
        #        answer = resolver.resolve(host)[0].to_text()
       #         address = (answer, port)
      #      except Exception as exc:
     #           print('dns.resolver: %s' % repr(exc))
    #        return orig_create_connection(address, *args, **kwargs)
   #     connection.create_connection = patched_create_connection
  #      CDN_PROXY = True
 #   except:
#        pass

SERVER_IP_FILE = "%s/server-ip.txt" % STORAGE_DIR
FAKE_DNS_FILE = "%s/fake-dns.txt" % STORAGE_DIR
ENABLE_BOTS_FILE = "%s/enable_bots.txt" % STORAGE_DIR`

This problem occurs when the zwift client is opened.
Which version of openssl is recommended?

**Comment by fatsbrown** [comment]
> Which version of openssl is recommended?

I use version 1.1.1f (Ubuntu 20.04.3).

Try setting MinProtocol to TLSv1.0 (see https://github.com/zoffline/zwift-offline?tab=readme-ov-file#extra-optional-steps).

**Comment by oldnapalm** [comment]
Closing due to lack of activity. Feel free to reopen if the issue still exists.
