### ISSUE TITLE
Regarding the issue of updating errors.

### ISSUE THREAD

**Issue by jricoclq** [zoffline/zwift-offline#343]
Hi
When running on the local computer, the recent updates have all encountered the situations in the logs, and they cannot be updated normally like previous versions. Please advise on how to set them up for normal updates.
![image](https://github.com/zoffline/zwift-offline/assets/102775665/3c2844bb-68e9-4573-9254-6a9a88c64701)
[logs.txt](https://github.com/user-attachments/files/16171006/logs.txt)

**Comment by fatsbrown** [comment]
I don't see any recent change in zoffline which could cause that error, it looks like some Google DNS restriction, because you can resolve some times but it eventually fails (LifetimeTimeout).

I suggest that you remove the line from hosts and update directly from the official server.

A possible fix would be implementing cache, like https://github.com/fatsbrown/zwift-offline/commit/59b90891e7f68e35ab148269b99d42b1306c296d

**Comment by fatsbrown** [comment]
Try with the latest commit (https://github.com/zoffline/zwift-offline/commit/cd8024ea5d57b4ca9c96e3ed82e56715ebebcd18), if that doesn't help you can try using another DNS instead of 8.8.8.8 (like 1.1.1.1 or the one from your internet provider).

**Comment by 346970897** [comment]
是的，我也遇到了这个问题

**Comment by 346970897** [comment]
yes,me too  
`2024-07-20T15:49:04Z <Greenlet at 0x2aedfbae020: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x2aedbe4c040)> failed with ConnectionResetError

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\gevent\baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\gevent\server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\gevent\ssl.py", line 836, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\gevent\ssl.py", line 349, in __init__
    self.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\gevent\ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-07-20T15:49:04Z <Greenlet at 0x2aedfbae020: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x2aedbe4c040)> failed with ConnectionResetError
`

**Comment by oldnapalm** [comment]
@346970897 I don't think this error is related to this issue. It looks like you didn't import the SSL certificate or didn't append it to cacert.pem properly (step 2 of README).

**Comment by oldnapalm** [comment]
This issue should be resolved in https://github.com/zoffline/zwift-offline/commit/cd8024ea5d57b4ca9c96e3ed82e56715ebebcd18, if it still exists I recommend [disabling zoffline](https://github.com/zoffline/zwift-offline?tab=readme-ov-file#enablingdisabling-zoffline) and updating Zwift directly from the official server before updating zoffline. The update proxy for a client running on the same machine as zoffline is a workaround that works for many but is not guaranteed to work in all cases. The official procedure documented in README consists in having the correct Zwift version already installed before running zoffline.
