### ISSUE TITLE
Docker down?

### ISSUE THREAD

**Issue by Vendo233** [zoffline/zwift-offline#386]

**Comment by fatsbrown** [comment]
It's working here. Maybe down in your area? Try again later.

**Comment by Vendo233** [comment]
Can`t connect, here is the log

`  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 836, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1000)
2024-11-18T21:07:34Z <Greenlet at 0x7e102a5039c0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7e1029bc813)> failed with SSLError
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.local/lib/python3.12/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 836, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1000)
2024-11-18T21:07:37Z <Greenlet at 0x7e102a5039c0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7e1029bc813)> failed with SSLError
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.local/lib/python3.12/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 836, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1000)
2024-11-18T21:07:39Z <Greenlet at 0x7e102a5039c0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7e1029bc813)> failed with SSLError
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.local/lib/python3.12/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 836, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1000)
2024-11-18T21:07:40Z <Greenlet at 0x7e102a5039c0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7e1029bc813)> failed with SSLError
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.local/lib/python3.12/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 836, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1000)
2024-11-18T21:07:44Z <Greenlet at 0x7e102a5039c0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7e1029bc813)> failed with SSLError
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.local/lib/python3.12/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
    return handle(*args_tuple)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/server.py", line 209, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 836, in wrap_socket
    return SSLSocket(sock=sock, keyfile=keyfile, certfile=certfile,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 349, in __init__
    self.do_handshake()
  File "/root/.local/lib/python3.12/site-packages/gevent/ssl.py", line 724, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1000)
2024-11-18T21:07:50Z <Greenlet at 0x7e102a5039c0: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x7e1029bc813)> failed with SSLError
`

**Comment by Vendo233** [comment]
[_zoffline_logs.txt](https://github.com/user-attachments/files/17806300/_zoffline_logs.txt)

**Comment by Vendo233** [comment]
it has been working fine, last night it couldn`t connect, tried updating docker , no luck

**Comment by Vendo233** [comment]
Trued parch the obv again, no luch

Whoah! Can't connect servers......

**Comment by fatsbrown** [comment]
This doesn't mean Docker is down.

Make sure the obb patch finished correctly. Try to clear app data (Android Settings - Applications - Zwift - Storage) and run ZofflineObb again.

**Comment by Vendo233** [comment]
This trick worked! Thank you

**Comment by fatsbrown** [comment]
It's in the `storage` folder (the one you passed in `-v` argument to `docker create` command or `volumes` if you used Docker Compose).

**Comment by Vendo233** [comment]
Thank you Sir, great work btw, with Strava and all the bots it works for me very good!

**Comment by zhangyue118** [comment]
> > What is ZofflineObb, how to use it and how can I get it
> 
> See README - Step 2 - Android (non-rooted device)

Sorry, I'm not Android. I installed it on windows
