### ISSUE TITLE
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

### ISSUE THREAD

**Issue by Stonekity** [zoffline/zwift-offline#401]
Windows:  zoffline_1.0.136993.exe
Android: com_zwift_zwiftgame_v1.0.136993

The zoffline background service on the computer is started normally, and the Virtual Hosts and ZofflineObb on the Android are successfully executed. However, when starting zwift, an exception occurs on the computer terminal, and the mobile phone zwift cannot connect to the computer service normally. What is the reason for this? I hope to receive a reply, thank you very much.

INFO:zoffline:server-ip.txt not found, using 192.168.1.14
INFO:zoffline:Server version 1.79.0 (136993) is running.
INFO:zoffline:192.168.1.13 - - [2024-12-18 23:19:01] "GET /gameassets/MapSchedule_v2.xml HTTP/1.1" 200 31055 0.103345
INFO:zoffline:192.168.1.13 - - [2024-12-18 23:19:01] "GET /gameassets/ZwiftAndroid_ver_cur.xml HTTP/1.1" 200 506 0.002318
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "gevent\baseserver.py", line 34, in _handle_and_close_when_done
  File "gevent\server.py", line 209, in wrap_socket_and_handle
  File "gevent\ssl.py", line 836, in wrap_socket
  File "gevent\ssl.py", line 349, in __init__
  File "gevent\ssl.py", line 724, in do_handshake
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-12-18T15:19:04Z <Greenlet at 0x15fd8594360: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x15fd8555240)> failed with ConnectionResetError

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "gevent\baseserver.py", line 34, in _handle_and_close_when_done
  File "gevent\server.py", line 209, in wrap_socket_and_handle
  File "gevent\ssl.py", line 836, in wrap_socket
  File "gevent\ssl.py", line 349, in __init__
  File "gevent\ssl.py", line 724, in do_handshake
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-12-18T15:19:09Z <Greenlet at 0x15fd8594180: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x15fd8555240)> failed with ConnectionResetError

Traceback (most recent call last):

**Comment by fatsbrown** [comment]
Are you sure the ZofflineObb patch finished successfully?

Try going to Android settings - applications - Zwift - storage, "clear data", then run ZofflineObb again.

**Comment by Stonekity** [comment]
> Are you sure the ZofflineObb patch finished successfully?
> 
> Try going to Android settings - applications - Zwift - storage, "clear data", then run ZofflineObb again.

Yes, the ZofflineObb log successfully printed 'Done'!
Uh huh, okay, I'll try running it again according to the method you said, and I'll sync the results with you later. Thank you very much

**Comment by fatsbrown** [comment]
> Yes, the ZofflineObb log successfully printed 'Done'!

Then you don't need to run ZofflineObb again, just "clear data" and run Zwift again (you should see "unzipping files"). This is to make sure the cacert.pem in use is from the patched obb and not from before ZofflineObb was run.

**Comment by Stonekity** [comment]
According to what you said, it can run normally now. It's really great. Thank you very much
