### ISSUE TITLE
OSError: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by Stonekity** [zoffline/zwift-offline#402]
When I start zwift-offline from source code on Mac, I often encounter this problem. Every time I need to restart the computer to run normally, what is the problem? I hope to get your reply, thank you very much!

```shell
➜  zwift-offline git:(master) ✗ sudo python3 standalone.py
INFO:zoffline:server-ip.txt not found, using 26.26.26.1
Traceback (most recent call last):
  File "/Users/stonekity/work/zwift/zwift-dev/server/zwift-offline/standalone.py", line 783, in <module>
    httpd = socketserver.ThreadingTCPServer(('', 80), CDNHandler)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
^CException ignored in: <module 'threading' from '/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1583, in _shutdown
    lock.acquire()
  File "/Users/stonekity/work/zwift/zwift-dev/server/zwift-offline/standalone.py", line 92, in sigint_handler
    httpd.shutdown()
    ^^^^^
NameError: name 'httpd' is not defined


➜  zwift-offline git:(master) ✗ sudo lsof -i -n -P
COMMAND     PID           USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
launchd       1           root   30u  IPv4 0x78c92689be3ab39      0t0  UDP *:137
launchd       1           root   31u  IPv4 0x78c92689be3ae49      0t0  UDP *:138
zerotier-    97           root    6u  IPv4 0x78c9263cfb0a389      0t0  TCP *:9993 (LISTEN)
zerotier-    97           root    7u  IPv6 0x78c92689c0bdc29      0t0  TCP *:9993 (LISTEN)
zerotier-    97           root    8u  IPv4 0x78c92689be3eb89      0t0  UDP 192.168.1.10:9993
zerotier-    97           root    9u  IPv4 0x78c92689be3ee99      0t0  UDP 192.168.1.10:50012
zerotier-    97           root   10u  IPv4 0x78c92689be3a519      0t0  UDP 192.168.1.10:64401
zerotier-    97           root   11u  IPv4 0x78c9263d0e79e31      0t0  TCP 26.26.26.1:64455->204.80.128.1:443 (ESTABLISHED)
systemsta   100           root   17u  IPv4 0x78c92689be3e879      0t0  UDP *:*
configd     102           root   16u  IPv4 0x78c92689be3a209      0t0  UDP *:*
configd     102           root   18u  IPv4 0x78c92689bfc1779      0t0  UDP *:*
configd     102           root   24u  IPv4 0x78c92689bfb4b89      0t0  UDP *:*
configd     102           root   25u  IPv4 0x78c92689c186779      0t0  UDP *:*
MainSvc     103           root   17u  IPv4 0x78c92689be3bd99      0t0  UDP *:*
syslogd     129           root   13u  IPv4 0x78c92689be3b779      0t0  UDP *:55639
ToDesk_Se   142           root    6u  IPv4 0x78c9263cfb0de31      0t0  TCP 127.0.0.1:35600 (LISTEN)
PerfPower   150           root   12u  IPv4 0x78c92689bfc3f49      0t0  UDP *:*
PerfPower   150           root   14u  IPv4 0x78c92689bfc0e49      0t0  UDP *:*
PerfPower   150           root   15u  IPv4 0x78c92689bfc1159      0t0  UDP *:*
PerfPower   150           root   16u  IPv4 0x78c92689bfc2ff9      0t0  UDP *:*
bluetooth   157           root   12u  IPv4 0x78c92689be3b159      0t0  UDP *:*
bluetooth   157           root   14u  IPv4 0x78c92689be3e569      0t0  UDP *:*
bluetooth   157           root   15u  IPv4 0x78c92689be3dc39      0t0  UDP *:*
AirPlayXP   161           root    3u  IPv4 0x78c92689be3c0a9      0t0  UDP *:*
loginwind   170      stonekity    7u  IPv4 0x78c92689bfbd6c9      0t0  UDP *:*
airportd    186           root    5u  IPv4 0x78c92689bfbec39      0t0  UDP *:*
airportd    186           root    6u  IPv4 0x78c92689be3b469      0t0  UDP *:*
airportd    186           root   12u  IPv6 0x78c92689bfb8c39      0t0  UDP *:*
airportd    186           root   13u  IPv4 0x78c92689bfb9e99      0t0  UDP *:*
airportd    186           root   15u  IPv4 0x78c92689bfabe49      0t0  UDP *:*
airportd    186           root   19u  IPv4 0x78c92689bfb6159      0t0  UDP *:*
airportd    186           root   22u  IPv4 0x78c92689bfac159      0t0  UDP *:*
airportd    186           root   26u  IPv4 0x78c92689bfbc159      0t0  UDP *:*
airportd    186           root   28u  IPv4 0x78c92689bfbc469      0t0  UDP *:*
airportd    186           root   30u  IPv4 0x78c92689bfbcd99      0t0  UDP *:*
airportd    186           root   32u  IPv4 0x78c92689bfb73b9      0t0  UDP *:*
airportd    186           root   35u  IPv4 0x78c92689bfb76c9      0t0  UDP *:*
symptomsd   233      _networkd   19u  IPv4 0x78c92689bfc29d9      0t0  UDP *:*
mDNSRespo   234 _mdnsresponder    6u  IPv4 0x78c92689be3cce9      0t0  UDP *:5353
mDNSRespo   234 _mdnsresponder    7u  IPv6 0x78c92689be3cff9      0t0  UDP *:5353
biometric   240           root    3u  IPv6 0x78c92689c0b4e29      0t0  TCP [fe80:4::aede:48ff:fe00:1122]:54055->[fe80:4::aede:48ff:fe33:4455]:52032 (ESTABLISHED)
xartstora   241           root    3u  IPv4 0x78c9263cfb0c8e1      0t0  TCP *:61500 (LISTEN)
xartstora   241           root    4u  IPv6 0x78c92689c0bf129      0t0  TCP *:61500 (LISTEN)
eoshostd    340           root    3u  IPv6 0x78c92689c0af329      0t0  TCP [fe80:4::aede:48ff:fe00:1122]:61885->[fe80:4::aede:48ff:fe33:4455]:61000 (ESTABLISHED)
locationd   342     _locationd    4u  IPv4 0x78c92689be3a829      0t0  UDP *:*
systemsta   427           root   17u  IPv4 0x78c92689be3e879      0t0  UDP *:*
ControlCe   455      stonekity   21u  IPv4 0x78c92689bfc0b39      0t0  UDP *:*
rapportd    482      stonekity    3u  IPv4 0x78c9263d0e358e1      0t0  TCP *:61869 (LISTEN)
rapportd    482      stonekity    4u  IPv6 0x78c92689c0b8829      0t0  TCP *:61869 (LISTEN)
rapportd    482      stonekity    5u  IPv4 0x78c92689bfc23b9      0t0  UDP *:*
rapportd    482      stonekity    6u  IPv4 0x78c92689bfc3619      0t0  UDP *:*
rapportd    482      stonekity   10u  IPv4 0x78c9263d0e3ae31      0t0  TCP 192.168.1.10:61869->192.168.1.9:51937 (ESTABLISHED)
rapportd    482      stonekity   11u  IPv4 0x78c92689bfaca89      0t0  UDP *:3722
rapportd    482      stonekity   12u  IPv4 0x78c92689bfbfb89      0t0  UDP *:*
rapportd    482      stonekity   13u  IPv4 0x78c92689be3c9d9      0t0  UDP *:*
cloudd      492      stonekity  175u  IPv4 0x78c9263d0e79389      0t0  TCP 26.26.26.1:64619->17.248.216.133:443 (ESTABLISHED)
cloudd      492      stonekity  176u  IPv4 0x78c9263d0e08389      0t0  TCP 26.26.26.1:64560->111.13.126.252:443 (ESTABLISHED)
cloudd      492      stonekity  177u  IPv4 0x78c9263d0e258e1      0t0  TCP 26.26.26.1:64566->111.13.126.252:443 (ESTABLISHED)
cloudd      492      stonekity  178u  IPv4 0x78c9263d0e4ee31      0t0  TCP 26.26.26.1:64570->111.13.126.252:443 (ESTABLISHED)
cloudd      492      stonekity  179u  IPv4 0x78c9263d19d08e1      0t0  TCP 26.26.26.1:64572->117.185.238.55:443 (ESTABLISHED)
identitys   493      stonekity   26u  IPv4 0x78c92689bfbf259      0t0  UDP *:*
identitys   493      stonekity   31u  IPv4 0x78c92689bfbb519      0t0  UDP *:*
identitys   493      stonekity   47u  IPv6 0x78c92689c0bc729      0t0  TCP [fe80:12::127a:e0f8:8379:4876]:1024->[fe80:12::7282:cf88:b5ba:90d6]:1024 (ESTABLISHED)
identitys   493      stonekity   51u  IPv6 0x78c92689c0b7a29      0t0  TCP [fe80:12::127a:e0f8:8379:4876]:1026->[fe80:12::7282:cf88:b5ba:90d6]:1025 (ESTABLISHED)
identitys   493      stonekity   52u  IPv6 0x78c92689c0b7a29      0t0  TCP [fe80:12::127a:e0f8:8379:4876]:1026->[fe80:12::7282:cf88:b5ba:90d6]:1025 (ESTABLISHED)
SogouServ   521      stonekity    3u  IPv4 0x78c9263d0e538e1      0t0  TCP 26.26.26.1:64574->120.241.139.215:80 (ESTABLISHED)
sharingd    530      stonekity    4u  IPv4 0x78c92689be3c6c9      0t0  UDP *:*
sharingd    530      stonekity    8u  IPv4 0x78c92689be3d309      0t0  UDP *:*
sharingd    530      stonekity    9u  IPv4 0x78c92689bfc4569      0t0  UDP *:*
sharingd    530      stonekity   10u  IPv4 0x78c92689bfc4879      0t0  UDP *:*
sharingd    530      stonekity   11u  IPv4 0x78c92689bfc26c9      0t0  UDP *:*
sharingd    530      stonekity   33u  IPv4 0x78c92689bfb6a89      0t0  UDP *:*
sharingd    530      stonekity   34u  IPv4 0x78c92689bfb7ce9      0t0  UDP *:*
WiFiAgent   554      stonekity    5u  IPv4 0x78c92689be3ba89      0t0  UDP *:*
WirelessR   563           root    3u  IPv4 0x78c92689bfc1469      0t0  UDP *:*
WirelessR   563           root    4u  IPv4 0x78c92689c183c39      0t0  UDP *:*
WirelessR   563           root    5u  IPv4 0x78c92689c183f49      0t0  UDP *:*
LetsVPN     617      stonekity   19u  IPv4 0x78c9263d0e8e8e1      0t0  TCP 192.168.1.10:64652->125.88.252.27:443 (ESTABLISHED)
LetsVPN     617      stonekity   25u  IPv4 0x78c92689bfab829      0t0  UDP 192.168.1.10:50416->120.226.165.140:443
LetsVPN     617      stonekity   26u  IPv4 0x78c9263d19d1e31      0t0  TCP 192.168.1.10:64620->125.88.252.27:443 (ESTABLISHED)
LetsVPN     617      stonekity   27u  IPv4 0x78c9263d0e69e31      0t0  TCP 192.168.1.10:64642->121.36.47.3:443 (ESTABLISHED)
LetsVPN     617      stonekity   38u  IPv4 0x78c9263cfae98e1      0t0  TCP 192.168.1.10:64571->111.13.126.252:443 (ESTABLISHED)
LetsVPN     617      stonekity   40u  IPv4 0x78c9263d19cfe31      0t0  TCP 192.168.1.10:64456->125.88.252.27:443 (ESTABLISHED)
LetsVPN     617      stonekity   42u  IPv4 0x78c9263d0e618e1      0t0  TCP 192.168.1.10:64573->117.185.238.55:443 (ESTABLISHED)
LetsVPN     617      stonekity   43u  IPv4 0x78c9263d0e13e31      0t0  TCP 192.168.1.10:64561->111.13.126.252:443 (ESTABLISHED)
LetsVPN     617      stonekity   47u  IPv4 0x78c9263d0e1a389      0t0  TCP 192.168.1.10:64567->111.13.126.252:443 (ESTABLISHED)
LetsVPN     617      stonekity   50u  IPv4 0x78c9263cfada389      0t0  TCP 192.168.1.10:64575->120.241.139.215:80 (ESTABLISHED)
LetsVPN     617      stonekity   71u  IPv4 0x78c9263d0e0e389      0t0  TCP 192.168.1.10:64304->125.88.252.27:443 (ESTABLISHED)
jetbrains   671      stonekity  125u  IPv6 0x78c92689c0b8f29      0t0  TCP 127.0.0.1:49335 (LISTEN)
jetbrains   671      stonekity  128u  IPv6 0x78c92689c0b9d29      0t0  TCP 127.0.0.1:52829 (LISTEN)
studio     2213      stonekity   41u  IPv6 0x78c92689c0c1429      0t0  TCP 127.0.0.1:63342 (LISTEN)
studio     2213      stonekity  190u  IPv6 0x78c92689bfb8f49      0t0  UDP *:58496
studio     2213      stonekity  232u  IPv6 0x78c92689c0bd529      0t0  TCP 127.0.0.1:61415->127.0.0.1:5037 (ESTABLISHED)
studio     2213      stonekity  237u  IPv6 0x78c92689c0b6529      0t0  TCP [::127.0.0.1]:55492->[::127.0.0.1]:52750 (CLOSED)
studio     2213      stonekity  260u  IPv6 0x78c92689bfbe309      0t0  UDP *:63487
studio     2213      stonekity  541u  IPv6 0x78c92689c0c2229      0t0  TCP 127.0.0.1:61419->127.0.0.1:5037 (ESTABLISHED)
studio     2213      stonekity  745u  IPv6 0x78c92689c0c2929      0t0  TCP 127.0.0.1:61420->127.0.0.1:5037 (ESTABLISHED)
studio     2213      stonekity  851u  IPv6 0x78c92689c0b4029      0t0  TCP 127.0.0.1:61440->127.0.0.1:5037 (ESTABLISHED)
studio     2213      stonekity  875u  IPv6 0x78c92689c0bab29      0t0  TCP [::127.0.0.1]:63364->[::127.0.0.1]:5037 (CLOSED)
WeChat     8358      stonekity   17u  IPv4 0x78c92689bfbf879      0t0  UDP *:*
WeChat     8358      stonekity   21u  IPv4 0x78c92689bfbd3b9      0t0  UDP *:*
WeChat     8358      stonekity  136u  IPv4 0x78c9263d01b18e1      0t0  TCP 26.26.26.1:56742->183.192.195.199:80 (CLOSE_WAIT)
WeChat     8358      stonekity  139u  IPv4 0x78c9263d0e06389      0t0  TCP 26.26.26.1:56744->183.192.195.235:80 (CLOSE_WAIT)
WeChat     8358      stonekity  149u  IPv4 0x78c9263d0e2ce31      0t0  TCP 26.26.26.1:56748->36.155.189.240:80 (CLOSE_WAIT)
WeChat     8358      stonekity  254u  IPv4 0x78c9263cfb08e31      0t0  TCP 26.26.26.1:55467->112.53.1.213:443 (CLOSE_WAIT)
WeChat     8358      stonekity  257u  IPv4 0x78c9263d0e49389      0t0  TCP 26.26.26.1:55468->120.232.131.227:443 (CLOSE_WAIT)
WeChat     8358      stonekity  265u  IPv4 0x78c9263d0e3de31      0t0  TCP 192.168.1.10:61895->36.155.184.206:443 (ESTABLISHED)
SunloginC 12659           root    4u  IPv4 0x78c92689bfc4e99      0t0  UDP 127.0.0.1:56866
assistant 13629      stonekity   39u  IPv4 0x78c92689be3c3b9      0t0  UDP *:*
adb       20261      stonekity    4u  IPv4 0x78c9263d0e8f389      0t0  TCP 127.0.0.1:5037->127.0.0.1:61415 (ESTABLISHED)
adb       20261      stonekity    9u  IPv4 0x78c9263d0e128e1      0t0  TCP 127.0.0.1:5037 (LISTEN)
adb       20261      stonekity   12u  IPv4 0x78c9263cfae68e1      0t0  TCP 127.0.0.1:5037->127.0.0.1:61419 (ESTABLISHED)
adb       20261      stonekity   13u  IPv4 0x78c9263cfafd8e1      0t0  TCP 127.0.0.1:5037->127.0.0.1:61420 (ESTABLISHED)
adb       20261      stonekity   14u  IPv4 0x78c9263d0e8b389      0t0  TCP 127.0.0.1:5037->127.0.0.1:61440 (ESTABLISHED)
com.apple 25452      stonekity   14u  IPv4 0x78c9263d018a389      0t0  TCP 26.26.26.1:64641->121.36.47.3:443 (ESTABLISHED)
com.apple 25452      stonekity   29u  IPv4 0x78c9263d0e0c389      0t0  TCP 26.26.26.1:59884->140.82.113.26:443 (ESTABLISHED)
com.apple 25452      stonekity   42u  IPv4 0x78c9263d0e3a389      0t0  TCP 26.26.26.1:64651->20.122.63.128:443 (ESTABLISHED)
com.apple 25452      stonekity   47u  IPv4 0x78c9263d0e058e1      0t0  TCP 26.26.26.1:62731->140.82.113.26:443 (ESTABLISHED)
QQ        27831      stonekity   40u  IPv4 0x78c9263d0e3c8e1      0t0  TCP 127.0.0.1:9210 (LISTEN)
QQ        27831      stonekity   47u  IPv4 0x78c92689bfaef49      0t0  UDP *:*
QQ        27831      stonekity   63u  IPv4 0x78c9263cfaf18e1      0t0  TCP 192.168.1.10:59813->36.155.163.51:443 (ESTABLISHED)
QQ        27831      stonekity   68u  IPv4 0x78c9263d0e8a8e1      0t0  TCP 127.0.0.1:4301 (LISTEN)
QQ        27831      stonekity   76u  IPv4 0x78c9263d0193e31      0t0  TCP 127.0.0.1:4310 (LISTEN)
QQ        27831      stonekity   80u  IPv4 0x78c92689bfacd99      0t0  UDP *:54254
QQ        27831      stonekity  164u  IPv4 0x78c92689bfaf569      0t0  UDP *:49348
QQ        27831      stonekity  165u  IPv4 0x78c92689bfad9d9      0t0  UDP *:58667
QQ        27831      stonekity  192u  IPv4 0x78c92689bfae619      0t0  UDP *:56653
QQ        27831      stonekity  193u  IPv4 0x78c92689bfab209      0t0  UDP *:62929
QQ        27831      stonekity  200u  IPv4 0x78c92689bfae309      0t0  UDP *:60764
QQ        27831      stonekity  202u  IPv4 0x78c92689bfafb89      0t0  UDP *:53935
QQ        27831      stonekity  203u  IPv4 0x78c92689bfaf259      0t0  UDP *:53608
QQ        27831      stonekity  204u  IPv4 0x78c92689bfad0a9      0t0  UDP *:57800
QQ        27831      stonekity  210u  IPv4 0x78c9263d0e71389      0t0  TCP 26.26.26.1:62560->120.238.93.131:49156 (CLOSE_WAIT)
QQ\x20Hel 27835      stonekity   21u  IPv4 0x78c92689bfab519      0t0  UDP 26.26.26.1:62298->120.226.165.140:443
Python    29329           root    4u  IPv4 0x78c9263d01b4389      0t0  TCP *:80 (LISTEN)
Python    29329           root    5u  IPv4 0x78c9263cfaed8e1      0t0  TCP *:3025 (LISTEN)
Python    29329           root    6u  IPv4 0x78c92689bfae929      0t0  UDP *:3024
Python    29329           root    7u  IPv4 0x78c92689bfaec39      0t0  UDP *:53
Python    29329           root   10u  IPv4 0x78c9263cfaeee31      0t0  TCP *:443 (LISTEN)
netbiosd  31542       _netbios    3u  IPv4 0x78c92689be3ab39      0t0  UDP *:137
netbiosd  31542       _netbios    4u  IPv4 0x78c92689be3ae49      0t0  UDP *:138
java      32695      stonekity  242u  IPv6 0x78c92689c0be329      0t0  TCP 127.0.0.1:63296 (LISTEN)
java      32695      stonekity  244u  IPv6 0x78c92689c189259      0t0  UDP *:50618
ZwiftLaun 33253      stonekity   18u  IPv4 0x78c9263cfb03389      0t0  TCP 192.168.1.10:52292->35.163.246.181:443 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   29u  IPv4 0x78c9263d0e2f8e1      0t0  TCP 192.168.1.10:64082->13.33.28.48:443 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   32u  IPv4 0x78c9263cfafe389      0t0  TCP 192.168.1.10:64083->13.33.28.48:443 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   43u  IPv4 0x78c9263d018c389      0t0  TCP 192.168.1.10:64087->3.165.82.47:80 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   46u  IPv4 0x78c9263cfadae31      0t0  TCP 192.168.1.10:64088->13.33.28.95:443 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   50u  IPv4 0x78c9263cfaf6389      0t0  TCP 192.168.1.10:64089->3.165.82.47:80 (ESTABLISHED)
ZwiftLaun 33253      stonekity   51u  IPv4 0x78c9263d0e36e31      0t0  TCP 192.168.1.10:64090->3.165.82.47:80 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   62u  IPv4 `0x78c9263d0e2a389`      0t0  TCP 192.168.1.10:64155->3.165.82.47:80 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   64u  IPv4 0x78c9263d01b2e31      0t0  TCP 192.168.1.10:64157->3.165.82.47:80 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   66u  IPv4 0x78c9263d019fe31      0t0  TCP 192.168.1.10:64158->3.165.82.47:80 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   68u  IPv4 0x78c9263cfaff8e1      0t0  TCP 192.168.1.10:64161->3.165.82.47:80 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   70u  IPv4 0x78c9263cfaee389      0t0  TCP 192.168.1.10:64162->3.165.82.47:80 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   74u  IPv4 0x78c9263d0e8be31      0t0  TCP 192.168.1.10:64172->3.165.82.42:80 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   78u  IPv4 0x78c9263cfb078e1      0t0  TCP 192.168.1.10:64177->3.165.82.42:80 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   80u  IPv4 0x78c9263d0e23389      0t0  TCP 192.168.1.10:64183->3.165.82.42:80 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   82u  IPv4 0x78c9263d0e89389      0t0  TCP 192.168.1.10:64187->3.165.82.42:80 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   86u  IPv4 0x78c9263d0e43e31      0t0  TCP 192.168.1.10:64192->3.165.82.42:80 (CLOSE_WAIT)
ZwiftLaun 33253      stonekity   88u  IPv4 0x78c9263d0e28389      0t0  TCP 192.168.1.10:64204->3.165.82.42:80 (CLOSE_WAIT)
netdisk_s 40862      stonekity   12u  IPv4 0x78c9263cfaf4e31      0t0  TCP 127.0.0.1:10000 (LISTEN)
wifiveloc 41348           root    3u  IPv4 0x78c92689c413f49      0t0  UDP *:*
```

**Comment by fatsbrown** [comment]
Looks like zoffline is already running in the background
```
Python    29329           root    4u  IPv4 0x78c9263d01b4389      0t0  TCP *:80 (LISTEN)
Python    29329           root    5u  IPv4 0x78c9263cfaed8e1      0t0  TCP *:3025 (LISTEN)
Python    29329           root    6u  IPv4 0x78c92689bfae929      0t0  UDP *:3024
Python    29329           root    7u  IPv4 0x78c92689bfaec39      0t0  UDP *:53
Python    29329           root   10u  IPv4 0x78c9263cfaeee31      0t0  TCP *:443 (LISTEN)
```

Run `sudo kill 29329` (or whichever the new PID is) to stop it before running `sudo python3 standalone.py` again.

Notice that if you only close the terminal, it's possible that zoffline keeps running in the background, you have to press Control+C to close zoffline first.

**Comment by Stonekity** [comment]
> Notice that if you only close the terminal, it's possible that zoffline keeps running in the background, you have to press Control+C to close zoffline first.

Thank you very much. I tested it and it is exactly the same as you said. I finally found the pattern and the problem is solved.
