### ISSUE TITLE
Cert issue - macOS

### ISSUE THREAD

**Issue by maciejzgadzaj** [zoffline/zwift-offline#68]
Running newest Zwift 1.0.53029, and freshly cloned zwift-offline, on macOS Sierra 10.12.6.

Followed the install/configure steps from README (including installing the new certificate in my keychain and granting it all permissions) - except opening `~/Library/Application Support/Zwift/data/cacert.pem` in the editor and manually appending `ssl/cert-zwift-com.pem` to it - instead I did what was suggested in issue #62 - `cat cert-zwift-com.pem >> cacert.pem`

When trying to start Zwift, it complains about "An SSL error has occured and a secure connection to the server cannot be made." Guess I'm not doing it quite right?

My `cacert.pem` after cat-ing  the `cert-zwift-com.pem` and opening it in TextMate looks like this (where it switches from original content to the new one): https://imgur.com/a/sV1gc7F

I have also tried removing all `<CR>`s, and replacing all double `<CR><CR>` with single `<CR>`, no luck either, same error in the end. Guess I might be doing something wrong?

Btw, even after doing above `cat` (and optional replacements) Zwift still works fine when connecting to its real servers (with the new `/etc/hosts` line commented out).

**Comment by oldnapalm** [comment]
I guess it should be `<CR><LF>`

cacert.pem contains `\r\r` (0D0D)
cert-zwift-com.pem contains `\r\n` (0D0A)

When I cat cert-zwift-com.pem >> cacert.pem it keeps `\r\n` and works.

![Captura de Tela 2020-07-01 às 15 02 46](https://user-images.githubusercontent.com/38410858/86276806-f60bed80-bbab-11ea-8b21-2e325fae119e.png)

**Comment by maciejzgadzaj** [comment]
Right, but <LF> is just a new line, isn't it? 

I am not really sure what else I could try, I think I have tried all possible options, and have run out of ideas...

Out of curiosity, mind sharing your full working `cacert.pem` file please?

**Comment by oldnapalm** [comment]
[cacert.pem.zip](https://github.com/zoffline/zwift-offline/files/4859682/cacert.pem.zip)

The hex editor is https://ridiculousfish.com/hexfiend/

**Comment by maciejzgadzaj** [comment]
Thank you! Just tried with your `cacert.pem`, same SSL error. Guess the issue might be somewhere else. But I got the certificate installed ok, always trusted, for all applications (https://imgur.com/a/GDjMOEm), not sure what might still be the issue...

**Comment by oldnapalm** [comment]
Which version of the Zwift launcher do you have? CFBundleVersion in /Applications/Zwift.app/Contents/Info.plist

Mine is 23. I had issues when updated from previous version (https://github.com/zoffline/zwift-offline/issues/27)

When Zwift updates its version (like 1.0.53029), the launcher isn't updated. Launcher is updated only if you download the app again.

**Comment by maciejzgadzaj** [comment]
23 as well. Can try to reinstall to see if it helps in any way.

**Comment by oldnapalm** [comment]
Is this the error you are getting?

![Captura de Tela 2020-07-01 às 15 55 57](https://user-images.githubusercontent.com/38410858/86281137-6ec27800-bbb3-11ea-8394-377db1761e64.png)

Isn't python being blocked by Little Snitch of other firewall?

**Comment by maciejzgadzaj** [comment]
Yes, that's exactly the one. I wouldn't think it's a firewall issue, not really running any here, and Zwift seems to connect to `standalone.py` server just fine, getting `127.0.0.1 - - [01/Jul/2020 20:19:05] "GET /gameassets/Zwift_Updates_Root/ HTTP/1.1" 200 -` each time I try to start it.

**Comment by oldnapalm** [comment]
That message is from cdn server (port 80), you should get `INFO:werkzeug:127.0.0.1 - - [01/Jul/2020 18:26:22] "GET /api/auth HTTP/1.1" 200 -` from auth server (port 443) right after.

Try to open https://secure.zwift.com/api/auth in Safari.

**Comment by maciejzgadzaj** [comment]
Trying to open https://secure.zwift.com/api/auth from Chrome I get `INFO:werkzeug:127.0.0.1 - - [01/Jul/2020 23:45:01] "GET /api/auth HTTP/1.1" 200 -`, but Chrome itself complains about invalid certificate: 
![Screen Shot 2020-07-01 at 23 47 15](https://user-images.githubusercontent.com/271350/86294719-6c810d80-bbf5-11ea-9437-d54f159fb77c.png)

**Comment by oldnapalm** [comment]
Chrome complains here too. Try in Safari.

**Comment by maciejzgadzaj** [comment]
Ah, fair enough. Safari returns `{"realm":"zwift","launcher":"https://launcher.zwift.com/launcher","url":"https://secure.zwift.com/auth/"}`

**Comment by maciejzgadzaj** [comment]
Then opening https://launcher.zwift.com/launcher gives me 
![Screen Shot 2020-07-02 at 00 03 12](https://user-images.githubusercontent.com/271350/86295687-760b7500-bbf7-11ea-861c-4bb70dc6d94a.png)

**Comment by oldnapalm** [comment]
How are you launching Zwift? Don't you get this launcher window?

**Comment by maciejzgadzaj** [comment]
Just launching the app in the usual way. All I get is this: 
![Screen Shot 2020-07-02 at 00 06 17](https://user-images.githubusercontent.com/271350/86295933-ee723600-bbf7-11ea-8d86-21e446b3af65.png)

**Comment by oldnapalm** [comment]
That's odd. Did you append the NSAppTransportSecurity key in /Applications/Zwift.app/Contents/Info.plist?

**Comment by maciejzgadzaj** [comment]
Yes:

`$ more /Applications/Zwift.app/Contents/Info.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>ATSApplicationFontsPath</key>
        <string>Fonts</string>
        <key>BuildMachineOSBuild</key>
        <string>15G31</string>
        <key>CFBundleDevelopmentRegion</key>
        <string>en</string>
        <key>CFBundleExecutable</key>
        <string>ZwiftLauncher-OSX</string>
        <key>CFBundleIconFile</key>
        <string>AppIcon</string>
        <key>CFBundleIdentifier</key>
        <string>com.zwift.ZwiftLauncher</string>
        <key>CFBundleInfoDictionaryVersion</key>
        <string>6.0</string>
        <key>CFBundleName</key>
        <string>Zwift</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>CFBundleShortVersionString</key>
        <string>1.0</string>
        <key>CFBundleSignature</key>
        <string>????</string>
        <key>CFBundleSupportedPlatforms</key>
        <array>
                <string>MacOSX</string>
        </array>
        <key>CFBundleURLTypes</key>
        <array>
                <dict>
                        <key>CFBundleURLName</key>
                        <string>com.zwift.ZwiftCustomProtocol</string>
                        <key>CFBundleURLSchemes</key>
                        <array>
                                <string>zcp</string>
                        </array>
                </dict>
        </array>
        <key>CFBundleVersion</key>
        <string>23</string>
        <key>DTCompiler</key>
        <string>com.apple.compilers.llvm.clang.1_0</string>
        <key>DTPlatformBuild</key>
        <string>7D1014</string>
        <key>DTPlatformVersion</key>
        <string>GM</string>
        <key>DTSDKBuild</key>
        <string>15E60</string>
        <key>DTSDKName</key>
        <string>macosx10.11</string>
        <key>DTXcode</key>
        <string>0731</string>
        <key>DTXcodeBuild</key>
        <string>7D1014</string>
        <key>LSApplicationCategoryType</key>
        <string>public.app-category.healthcare-fitness</string>
        <key>LSMinimumSystemVersion</key>
        <string>10.10</string>
        <key>NSHumanReadableCopyright</key>
        <string>Copyright © 2016 Zwift. All rights reserved.</string>
        <key>NSMainNibFile</key>
        <string>MainMenu</string>
        <key>NSPrincipalClass</key>
        <string>NSApplication</string>
        <key>NSAppTransportSecurity</key>
        <dict>
                <key>NSExceptionDomains</key>
                <dict>
                        <key>zwift.com</key>
                        <dict>
                                <key>NSExceptionAllowsInsecureHTTPLoads</key>
                                <true/>
                                <key>NSIncludesSubdomains</key>
                                <true/>
                        </dict>
                </dict>
        </dict>
</dict>
</plist>
`

**Comment by oldnapalm** [comment]
You might try, but mine is exactly like that and it's working.

It's strange that Safari can access the server but Zwift app can't.

Try with this just to make sure the problem isn't in the app
[Zwift.zip](https://github.com/zoffline/zwift-offline/files/4860925/Zwift.zip)

**Comment by maciejzgadzaj** [comment]
Also, nothing gets written to `~/Documents/Zwift/Logs/Log.txt` nor `Curl_Log.txt`, and `Launcher_log.txt` gets only this:

```
[0:20:12 2020-07-02] Launcher: Initializing Mac Timer.
[0:20:12 2020-07-02] Launcher: Checking for game version number.
[0:20:12 2020-07-02] Launcher: Checking for launcher version number.
[0:20:12 2020-07-02] Launcher: Checking for VerCur Override
[0:20:12 2020-07-02] Launcher: No VerCur Override Found.
[0:20:12 2020-07-02] Downloader::InternetConnected() returns TRUE![0:20:12 2020-07-02] Launcher: Established Internet Connection
```

**Comment by maciejzgadzaj** [comment]
Ha, now that's interesting - tried yours, with the following effect:

![Screen Shot 2020-07-02 at 00 23 44](https://user-images.githubusercontent.com/271350/86296968-67728d00-bbfa-11ea-95d5-fe106d26b6e5.png)

Which reminds that I was supposed to try reinstalling...

**Comment by oldnapalm** [comment]
Do you see anything in zoffline log if you run this?
`open ~/Library/Application\ Support/Zwift/ZwiftApp`

**Comment by maciejzgadzaj** [comment]
It shown just this:

```
127.0.0.1 - - [02/Jul/2020 00:30:32] "GET /gameassets/MapSchedule_v2.xml HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2020 00:30:32] "GET /gameassets/Streaming/Zwift_StreamingFiles_ver_cur.xml HTTP/1.1" 200 -
```

but the output of your command was pretty long - want me to gist it?

Also, it started Zwift this time, which got to the "Log in" screen, but "Failed to log in. Check internet connection."

**Comment by oldnapalm** [comment]
Try to log in using 1000 as username and no password, and check zoffline log.

**Comment by maciejzgadzaj** [comment]
Still "Failed to log in", nothing more in zoffline log (except those 2 lines above).

**Comment by oldnapalm** [comment]
It may be something related to the macOS version, I'm on 10.13.6.

Once I installed in 10.11 and if I remember correctly I had to import the .pem instead of the .p12 file in Keychain, but it was because it would not accept the .p12 with no password. You can try that.

**Comment by maciejzgadzaj** [comment]
Thanks for all this!

Just run few more tests:

- no difference between .pem and .p12, still the same error - it's just that .pem doesn't ask for password
- tried your localhost certs, no help
- tried generating new one using the medium link, still the same error
- tried your Zwift.app with Gatekeeper disabled, same result
- tried running it without changes to Info.plist, nada
- my SIP has been disabled all the time before

Looks like we're hitting a wall here... or missing something super obvious, as it's usually the case. :)

**Comment by oldnapalm** [comment]
The most strange thing is that you can reach the 443 server using Chrome or Safari but Zwift app can't.

Are you using default macOS Python or did you download from python.org? Not sure if it could make any difference but at this point I'm out of ideas.

**Comment by maciejzgadzaj** [comment]
I'm running zoffline with Python 2.7.10 0 - I believe it's system's default - as when I tried to install all python3 dependencies, it was failing on `google` - even though it was already installed:

```
$ pip3 install google
Requirement already satisfied: google in /usr/local/lib/python3.7/site-packages (2.0.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/site-packages (from google) (4.9.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.7/site-packages (from beautifulsoup4->google) (2.0.1)
```

zoffline was complaining it was not:

```
$ sudo python3 standalone.py 
Traceback (most recent call last):
  File "standalone.py", line 18, in <module>
    import zwift_offline
  File "/private/var/www/zwift-offline/zwift_offline.py", line 20, in <module>
    from google.protobuf.descriptor import FieldDescriptor
ModuleNotFoundError: No module named 'google'
```

Anyway, default python prints:

```
$ python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 0.9.8zh 14 Jan 2016
```

but even python3 seems to be ok:

```
$ python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by oldnapalm** [comment]
Maybe this OpenSSL version is too old.

Did you run `pip3 install flask protobuf protobuf3_to_dict stravalib` ?

**Comment by maciejzgadzaj** [comment]
Ok, so just re-done the install process with pip3, and we have progress:

```
$ sudo python3 standalone.py 
Password:
 * Serving Flask app "zwift_offline" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on https://0.0.0.0:443/ (Press CTRL+C to quit)
127.0.0.1 - - [02/Jul/2020 20:04:40] "GET /gameassets/Zwift_Updates_Root/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 20:04:40] "GET /api/auth HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 20:04:40] "GET /launcher/realms/zwift/protocol/openid-connect/auth?client_id=Game_Launcher&redirect_uri=http%3A%2F%2Fzwift%2F&login=true&response_type=code HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2020 20:04:41] "GET /gameassets/Zwift_Updates_Root/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2020 20:04:41] "GET /gameassets/Zwift_Updates_Root/ZwiftMac_ver_cur.xml HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2020 20:04:41] "GET /gameassets/Zwift_Updates_Root/LauncherMac_ver_cur.xml HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 20:04:50] "POST /start-zwift HTTP/1.1" 302 -
127.0.0.1 - - [02/Jul/2020 20:04:50] "GET /FRANCE HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 20:04:50] "GET /ride HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 20:04:50] "POST /auth/realms/zwift/protocol/openid-connect/token HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 20:04:50] "GET /static/web/launcher/embed.html HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2020 20:04:51] "GET /gameassets/MapSchedule_v2.xml HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2020 20:05:01] "GET /gameassets/Streaming/Zwift_StreamingFiles_ver_cur.xml HTTP/1.1" 200 -
```

Zwift launches, gives me profile/world selection page, and the gets to the log in page - where I can't sign in with my u/p, and 1000/no password doesn't work either.

I've fetched my `profile.bin` and put it in `storage`, but looking at dir listing now apparently at one point it has been moved to `storage/<id>/` - but as long as I've seen my profile on the initial step, I guess it's not really a problem.

**Comment by oldnapalm** [comment]
> Zwift launches, gives me profile/world selection page, and then gets to the log in page - where I can't sign in with my u/p, and 1000/no password doesn't work either.

Now the problem seems to be in cacert.pem, did you append the cert?

> I've fetched my `profile.bin` and put it in `storage`, but looking at dir listing now apparently at one point it has been moved to `storage/<id>/` - but as long as I've seen my profile on the initial step, I guess it's not really a problem?

This is the normal behavior
https://github.com/zoffline/zwift-offline/blob/a8c45f28a269bae90549585f2e6bef7627256dee/zwift_offline.py#L705

**Comment by maciejzgadzaj** [comment]
> Now the problem seems to be in cacert.pem, did you append the cert?

Yes, tried both with appending with `cat ssl/cert-zwift-com.pem >> ~/Library/Application\ Support/Zwift/data/cacert.pem`, as well as with your `cacert.pem` from yesterday - in both cases I'm getting the log in modal.

I guess I should not be seeing it at all?

**Comment by oldnapalm** [comment]
You should not see the log in screen.

Try installing Python 2.7.18 or 3.8.3 from python.org

The problem of launcher unable to access https server seemed to be due to OpenSSL version.

I'm using:

Python 2.7.18
OpenSSL 1.0.2u  20 Dec 2019

or

Python 3.8.2
OpenSSL 1.1.1d  10 Sep 2019

**Comment by maciejzgadzaj** [comment]
Installed current 3 version:

```
$ python3 --version
Python 3.8.3
$ python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.1.1g  21 Apr 2020
```

and I am really sorry to say I'm still getting stuck on the log in screen...

**Comment by oldnapalm** [comment]
Do you see any errors in Zwift log.txt?

Without the cert added (or with the line end issue) I see this

```
[15:55:20] NETCLIENT:[ERROR] Curl error: [77] 'Problem with the SSL CA cert (path? access rights?)' for: GET https://us-or-rly101.zwift.com/api/auth
[15:55:20] NETCLIENT:[ERROR] Error finding authorization server: [29] Problem with the SSL CA cert (path? access rights?)
```

**Comment by maciejzgadzaj** [comment]
Ok, so before `openssl version` was showing my some older 0.9.something (closed the tab after force-linking to the newer version). Now:

```
$ openssl version
OpenSSL 1.1.1g  21 Apr 2020
```

I have also re-fetched my profile, just in case.

Now, something as changed, I still end up on a log in screen, but with longer zoffline log:

```
$ sudo python3 standalone.py 
Password:
 * Serving Flask app "zwift_offline" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on https://0.0.0.0:443/ (Press CTRL+C to quit)
127.0.0.1 - - [02/Jul/2020 21:36:27] "GET /gameassets/Zwift_Updates_Root/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:27] "GET /api/auth HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:27] "GET /launcher/realms/zwift/protocol/openid-connect/auth?client_id=Game_Launcher&redirect_uri=http%3A%2F%2Fzwift%2F&login=true&response_type=code HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2020 21:36:28] "GET /gameassets/Zwift_Updates_Root/ HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2020 21:36:28] "GET /gameassets/Zwift_Updates_Root/ZwiftMac_ver_cur.xml HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2020 21:36:28] "GET /gameassets/Zwift_Updates_Root/LauncherMac_ver_cur.xml HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:30] "POST /start-zwift HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:30] "GET /ride HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:30] "POST /auth/realms/zwift/protocol/openid-connect/token HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:31] "GET /static/web/launcher/resources/js/royalslider/royalslider.css HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:31] "GET /static/web/launcher/resources/js/royalslider/jquery-1.8.3.min.js HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:31] "GET /static/web/launcher/resources/js/royalslider/jquery.royalslider.min.js HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:31] "GET /static/web/launcher/resources/css/smoothness/jquery-ui-1.8.22.custom.css HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:31] "GET /static/web/launcher/resources/js/royalslider/skins/minimal-white/rs-minimal-white.css HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:31] "GET /static/web/launcher/resources/js/royalslider/skins/default/rs-default.css HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:31] "GET /static/web/launcher/resources/v2.0/css/application.css HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:31] "GET /static/web/launcher/resources/images/oct17/launcherslides-oct17-1.jpg HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:31] "GET /static/web/launcher/resources/images/2020/Jul01/launcher_image_tdf.jpg HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:31] "GET /static/web/launcher/resources/images/Dec21/launcher-dec18-support.jpg HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:31] "GET /static/web/launcher/resources/images/Dec21/launcher-dec18-zc.jpg HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 21:36:31] "GET /static/web/launcher/resources/images/Dec21/launcher-dec18-ecomm.jpg HTTP/1.1" 404 -
127.0.0.1 - - [02/Jul/2020 21:36:31] "GET /gameassets/MapSchedule_v2.xml HTTP/1.1" 200 -
127.0.0.1 - - [02/Jul/2020 21:36:41] "GET /gameassets/Streaming/Zwift_StreamingFiles_ver_cur.xml HTTP/1.1" 200 -
```

and Zwift's `NETCLIENT` also started to complain in `Log.txt`: https://gist.github.com/maciejzgadzaj/290c1a99601d5f2155dd3bbbcd78e12a#file-log-txt-L1008

**Comment by oldnapalm** [comment]
I guess it may be a compatibility issue between OpenSSL versions.

Did you try with Python 2.7.18 and OpenSSL 1.0?

My `openssl version`
LibreSSL 2.2.7

**Comment by maciejzgadzaj** [comment]
Ok, so:

I tried with python2:

```
$ python2 --version
Python 2.7.18
```

same effects, Zwift wants me to log in.

I have installed both new `openssl` and `curl-openssl` with brew - but both are keg-only - so I can't force-link them to override default system's version.

Which means, that when I do what `brew info` suggests, and:

```
echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> /Users/mzgadzaj/.bash_profile
echo 'export PATH="/usr/local/opt/curl-openssl/bin:$PATH"' >> /Users/mzgadzaj/.bash_profile
```

and open new shell, what I'm getting is:

```
$ openssl version
OpenSSL 1.1.1g  21 Apr 2020
$ curl -V
curl 7.71.1 (x86_64-apple-darwin16.7.0) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.8 brotli/1.0.7 c-ares/1.16.1 libidn2/2.3.0 libssh2/1.9.0 nghttp2/1.41.0 librtmp/2.3
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

Without the exports though:

```
$ openssl version
OpenSSL 0.9.8zh 14 Jan 2016
$ curl -V
curl 7.54.0 (x86_64-apple-darwin16.0) libcurl/7.54.0 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets 
```

Not sure if Zwift heeds those exports? I would guess not really. 

Anyway, just in case also tried restarting the whole system, but still getting those pesky `Peer certificate cannot be authenticated with given CA certificates` errors in `Log.txt`.

Also tried copying both `cert-zwift-com.p12` and `cert-zwift-com.pem` files in `/usr/local/etc/openssl@1.1/certs` and `c_rehash`ing (which btw complained that `WARNING: cert-zwift-com.p12 does not contain a certificate or CRL: skipping`), no progress.

And yes, I can see `dyld: loaded: /usr/lib/libssl.35.dylib` as well: https://gist.github.com/maciejzgadzaj/f74d94da71a4065bf782286217d35764#file-dylds-L215

**Comment by oldnapalm** [comment]
The error in Log.txt is the same with or without cert appended to Zwift cacert.pem?

**Comment by zoffline** [comment]
Closing due to lack of activity.
